// =============================================================================
// NutriPlan — 28 Recetas Fitness
// Contenido estático incluido en tiers $9.90+.
// Número impar intencional: genera más curiosidad que una cifra redonda.
// =============================================================================

export interface Recipe {
  id: string
  name: string
  category: 'desayuno' | 'almuerzo' | 'cena' | 'snack'
  prepMin: number
  cookMin: number
  kcal: number
  protein: number  // g
  carbs: number    // g
  fat: number      // g
  ingredients: string[]
  steps: string[]
  tip?: string
}

export const RECIPES: Recipe[] = [
  // ─── DESAYUNOS ──────────────────────────────────────────────────────────────
  {
    id: 'des-01',
    name: 'Bowl de avena proteica con plátano y almendras',
    category: 'desayuno',
    prepMin: 3,
    cookMin: 5,
    kcal: 380,
    protein: 25,
    carbs: 48,
    fat: 10,
    ingredients: [
      '60 g avena en hojuelas',
      '1 scoop proteína de vainilla (30 g)',
      '1 plátano maduro',
      '10 almendras',
      '250 ml agua o leche descremada',
    ],
    steps: [
      'Cocina la avena con el agua o la leche a fuego medio por 5 minutos, revolviendo para que no se pegue.',
      'Retira del fuego y mezcla con el scoop de proteína hasta integrar bien.',
      'Sirve en un bowl, agrega el plátano en rodajas y las almendras encima.',
    ],
    tip: 'Prepara la avena la noche anterior con leche fría (overnight oats) y solo mezcla la proteína al servir.',
  },
  {
    id: 'des-02',
    name: 'Tortilla de 3 huevos con espinacas y pimentón',
    category: 'desayuno',
    prepMin: 3,
    cookMin: 7,
    kcal: 290,
    protein: 22,
    carbs: 5,
    fat: 19,
    ingredients: [
      '3 huevos',
      '1 taza espinacas baby',
      '½ pimentón rojo en tiras',
      '½ cdita aceite de oliva',
      'Sal y pimienta al gusto',
    ],
    steps: [
      'Bate los huevos con sal y pimienta hasta obtener una mezcla uniforme.',
      'Calienta el aceite en una sartén antiadherente a fuego medio y saltea el pimentón y las espinacas por 2 minutos.',
      'Vierte los huevos batidos encima y cocina a fuego bajo, tapando la sartén, hasta que cuajen por completo.',
    ],
  },
  {
    id: 'des-03',
    name: 'Panquecas de avena y banana',
    category: 'desayuno',
    prepMin: 5,
    cookMin: 10,
    kcal: 340,
    protein: 18,
    carbs: 52,
    fat: 7,
    ingredients: [
      '80 g avena en hojuelas',
      '1 plátano maduro aplastado con tenedor',
      '2 huevos',
      '½ cdita polvo de hornear',
      'Pizca de canela',
    ],
    steps: [
      'Licúa la avena, el plátano, los huevos, el polvo de hornear y la canela hasta obtener una mezcla homogénea.',
      'Calienta una sartén antiadherente a fuego medio-bajo sin aceite.',
      'Vierte porciones de ⅓ de taza y cocina 2-3 minutos por lado, hasta que estén doradas.',
    ],
    tip: 'Acompaña con fruta fresca picada o 1 cdita de miel de abeja para subir el sabor sin exceso de calorías.',
  },
  {
    id: 'des-04',
    name: 'Tostadas de aguacate con huevo pochado',
    category: 'desayuno',
    prepMin: 5,
    cookMin: 5,
    kcal: 350,
    protein: 16,
    carbs: 28,
    fat: 20,
    ingredients: [
      '2 rebanadas pan integral',
      '½ aguacate maduro',
      '2 huevos',
      '½ limón (jugo)',
      'Sal, pimienta negra y hojuelas de chile al gusto',
    ],
    steps: [
      'Tuesta las rebanadas de pan hasta que estén doradas y crujientes.',
      'Aplasta el aguacate con el jugo de limón, sal y pimienta hasta obtener una pasta rústica.',
      'Pocha los huevos en agua hirviendo con un chorrito de vinagre por 3-4 minutos para yema semilíquida.',
      'Monta: pan, aguacate, huevo pochado encima. Termina con hojuelas de chile.',
    ],
  },
  {
    id: 'des-05',
    name: 'Yogur griego con granola y fresas',
    category: 'desayuno',
    prepMin: 3,
    cookMin: 0,
    kcal: 320,
    protein: 22,
    carbs: 36,
    fat: 8,
    ingredients: [
      '200 g yogur griego natural sin azúcar',
      '30 g granola (preferiblemente sin azúcar añadida)',
      '1 taza fresas en rodajas',
      '1 cdita miel (opcional)',
    ],
    steps: [
      'Sirve el yogur griego en un bowl amplio.',
      'Agrega las fresas encima del yogur.',
      'Espolvorea la granola justo al momento de servir para que conserve el crujido. Rocía la miel si deseas.',
    ],
    tip: 'Cambia las fresas por mango, papaya o frutos rojos según la temporada. El yogur griego tiene el doble de proteína que el yogur común.',
  },
  {
    id: 'des-06',
    name: 'Smoothie de proteína con plátano y mantequilla de maní',
    category: 'desayuno',
    prepMin: 3,
    cookMin: 0,
    kcal: 420,
    protein: 32,
    carbs: 44,
    fat: 12,
    ingredients: [
      '1 scoop proteína de chocolate o vainilla (30 g)',
      '1 plátano mediano congelado',
      '1 cdita mantequilla de maní natural',
      '250 ml leche descremada',
      '3-4 cubos de hielo',
    ],
    steps: [
      'Agrega todos los ingredientes a la licuadora en el orden indicado.',
      'Licúa a velocidad alta por 30-45 segundos hasta obtener una textura cremosa.',
      'Sirve de inmediato y consume antes de que pierda la espuma.',
    ],
    tip: 'Congela el plátano la noche anterior para una textura más cremosa, parecida a un helado. Elige mantequilla de maní cuyo único ingrediente sea el maní.',
  },
  {
    id: 'des-07',
    name: 'Arepa con huevo revuelto y queso fresco',
    category: 'desayuno',
    prepMin: 3,
    cookMin: 8,
    kcal: 360,
    protein: 20,
    carbs: 40,
    fat: 12,
    ingredients: [
      '1 arepa de maíz precocido (60 g)',
      '2 huevos',
      '30 g queso fresco desmoronado',
      '½ cdita aceite de coco o mantequilla',
      'Sal y pimienta al gusto',
    ],
    steps: [
      'Calienta la arepa en una sartén o tostadora hasta que esté dorada por fuera.',
      'En la misma sartén con el aceite, revuelve los huevos a fuego bajo con sal y pimienta. Retira antes de que queden secos.',
      'Sirve los huevos revueltos sobre la arepa y espolvorea el queso fresco encima.',
    ],
  },

  // ─── ALMUERZOS ──────────────────────────────────────────────────────────────
  {
    id: 'alm-01',
    name: 'Bowl de pollo a la plancha con arroz integral y brócoli',
    category: 'almuerzo',
    prepMin: 5,
    cookMin: 20,
    kcal: 480,
    protein: 42,
    carbs: 52,
    fat: 8,
    ingredients: [
      '150 g pechuga de pollo',
      '80 g arroz integral cocido',
      '1 taza brócoli en floretes',
      'Ajo en polvo, sal y pimienta',
      '½ cdita aceite de oliva',
    ],
    steps: [
      'Sazona el pollo con ajo en polvo, sal y pimienta.',
      'Dóralo en la plancha o sartén con el aceite, 6-7 minutos por lado, hasta que esté bien cocido.',
      'Cocina el brócoli al vapor por 4 minutos: debe quedar tierno pero firme.',
      'Arma el bowl con el arroz como base, el pollo cortado en tiras y el brócoli al lado.',
    ],
  },
  {
    id: 'alm-02',
    name: 'Ensalada mediterránea de atún con garbanzos',
    category: 'almuerzo',
    prepMin: 8,
    cookMin: 0,
    kcal: 380,
    protein: 32,
    carbs: 30,
    fat: 12,
    ingredients: [
      '1 lata atún en agua (120 g drenado)',
      '½ taza garbanzos cocidos o de lata escurridos',
      '1 tomate mediano en cubos',
      '½ pepino en rodajas',
      'Aceitunas negras al gusto',
      '1 cdita aceite de oliva y jugo de ½ limón',
    ],
    steps: [
      'Escurre bien el atún y los garbanzos.',
      'Mezcla todos los ingredientes en un bowl grande.',
      'Aliña con el aceite de oliva, el jugo de limón, sal y pimienta. Mezcla y sirve frío.',
    ],
    tip: 'Esta ensalada aguanta refrigerada hasta 24 horas. Prepara doble porción para el día siguiente.',
  },
  {
    id: 'alm-03',
    name: 'Wrap de pollo con aguacate y vegetales',
    category: 'almuerzo',
    prepMin: 8,
    cookMin: 5,
    kcal: 420,
    protein: 35,
    carbs: 38,
    fat: 14,
    ingredients: [
      '1 tortilla integral grande (o de maíz)',
      '130 g pechuga de pollo cocida en tiras',
      '¼ aguacate en rodajas',
      'Hojas de lechuga o espinaca',
      '2 cdas pico de gallo (tomate, cebolla, cilantro)',
    ],
    steps: [
      'Calienta la tortilla en una sartén seca por 30 segundos por lado.',
      'Pon las hojas de lechuga como base en el centro de la tortilla.',
      'Agrega el pollo, el aguacate y el pico de gallo.',
      'Enrolla firmemente, dobla los extremos hacia adentro y corta al medio en diagonal.',
    ],
  },
  {
    id: 'alm-04',
    name: 'Sopa de lentejas con zanahoria y espinacas',
    category: 'almuerzo',
    prepMin: 5,
    cookMin: 30,
    kcal: 320,
    protein: 20,
    carbs: 46,
    fat: 5,
    ingredients: [
      '½ taza lentejas crudas (enjuagadas)',
      '1 zanahoria mediana en cubos',
      '1 taza espinacas frescas',
      '2 dientes de ajo, ½ cebolla picada',
      'Sal, comino y paprika al gusto',
      '600 ml agua o caldo de verduras',
    ],
    steps: [
      'En una olla, sofríe la cebolla y el ajo con una pizca de sal por 3 minutos.',
      'Agrega la zanahoria y las lentejas. Cubre con el caldo y lleva a hervor.',
      'Baja el fuego y cocina 20-25 minutos, hasta que las lentejas estén tiernas.',
      'Agrega las espinacas y el comino, cocina 2 minutos más y rectifica sal.',
    ],
  },
  {
    id: 'alm-05',
    name: 'Arroz con pollo y vegetales salteados',
    category: 'almuerzo',
    prepMin: 5,
    cookMin: 15,
    kcal: 460,
    protein: 38,
    carbs: 50,
    fat: 10,
    ingredients: [
      '150 g pechuga de pollo en cubos',
      '80 g arroz integral cocido',
      '½ taza ejotes o vainitas',
      '½ pimentón en tiras',
      '½ taza maíz dulce',
      'Sal, pimienta, comino y ½ cdita aceite',
    ],
    steps: [
      'Saltea el pollo en cubos con sal y pimienta en la sartén caliente, 5-6 minutos.',
      'Agrega los vegetales y saltea 4 minutos más, hasta que estén tiernos pero con textura.',
      'Incorpora el arroz cocido, mezcla bien y ajusta sal y comino. Saltea 1-2 minutos más.',
    ],
  },
  {
    id: 'alm-06',
    name: 'Filete de tilapia con quinoa y ejotes',
    category: 'almuerzo',
    prepMin: 5,
    cookMin: 12,
    kcal: 400,
    protein: 38,
    carbs: 38,
    fat: 9,
    ingredients: [
      '150 g filete de tilapia (o cualquier pescado blanco)',
      '80 g quinoa cocida',
      '1 taza ejotes cocidos al vapor',
      '½ limón, 1 diente de ajo rallado',
      'Sal, pimienta y ½ cdita aceite de oliva',
    ],
    steps: [
      'Sazona la tilapia con el ajo, sal, pimienta y el jugo de limón.',
      'Cocina en sartén con el aceite a fuego medio-alto, 4 minutos por lado, hasta dorar bien.',
      'Sirve el pescado sobre la quinoa con los ejotes al lado. Exprime limón extra al servir.',
    ],
    tip: 'La quinoa tiene todos los aminoácidos esenciales y combina perfecto con pescado para una comida alta en proteína completa.',
  },
  {
    id: 'alm-07',
    name: 'Ensalada de pechuga con aguacate y pico de gallo',
    category: 'almuerzo',
    prepMin: 8,
    cookMin: 12,
    kcal: 350,
    protein: 34,
    carbs: 12,
    fat: 18,
    ingredients: [
      '140 g pechuga de pollo',
      '½ aguacate en rodajas',
      '2 tazas mezcla de lechugas',
      '½ taza pico de gallo (tomate, cebolla, cilantro)',
      'Jugo de 1 limón y sal',
    ],
    steps: [
      'Sazona el pollo y cocínalo a la plancha 6 minutos por lado. Deja reposar 3 minutos y corta en tiras.',
      'Arma la ensalada con las lechugas como base.',
      'Agrega el pollo, el aguacate en rodajas y el pico de gallo encima.',
      'Aliña con jugo de limón y sal al gusto. No uses aderezos cremosos.',
    ],
  },

  // ─── CENAS ──────────────────────────────────────────────────────────────────
  {
    id: 'cen-01',
    name: 'Salmón al horno con espárragos y limón',
    category: 'cena',
    prepMin: 5,
    cookMin: 18,
    kcal: 380,
    protein: 36,
    carbs: 8,
    fat: 22,
    ingredients: [
      '150 g filete de salmón',
      '8 espárragos frescos',
      '1 limón (jugo y ralladura)',
      '1 diente de ajo picado fino',
      'Sal, pimienta y 1 cdita aceite de oliva',
    ],
    steps: [
      'Precalienta el horno a 200 °C.',
      'Coloca el salmón y los espárragos en una bandeja. Rocía con el aceite, el jugo de limón y el ajo. Sazona con sal y pimienta.',
      'Hornea 15-18 minutos, hasta que el salmón esté opaco en el centro y los espárragos tiernos.',
    ],
    tip: 'El salmón es rico en omega-3. Ideal 2-3 veces por semana para controlar inflamación y mejorar la composición corporal.',
  },
  {
    id: 'cen-02',
    name: 'Pollo al horno con camote y ensalada verde',
    category: 'cena',
    prepMin: 8,
    cookMin: 30,
    kcal: 420,
    protein: 38,
    carbs: 34,
    fat: 10,
    ingredients: [
      '150 g pechuga de pollo',
      '1 camote mediano en cubos (180 g)',
      '2 tazas mezcla de lechugas',
      'Paprika, ajo en polvo, sal',
      '1 cdita aceite de oliva y jugo de ½ limón',
    ],
    steps: [
      'Precalienta el horno a 200 °C.',
      'Marina el pollo con paprika, ajo en polvo y sal. Coloca junto al camote en una bandeja con el aceite.',
      'Hornea 25-30 minutos, volteando el camote a mitad de tiempo.',
      'Sirve con la ensalada aliñada con limón y sal.',
    ],
  },
  {
    id: 'cen-03',
    name: 'Bowl de carne molida magra con frijoles y arroz',
    category: 'cena',
    prepMin: 5,
    cookMin: 15,
    kcal: 450,
    protein: 35,
    carbs: 46,
    fat: 12,
    ingredients: [
      '150 g carne molida magra (90/10)',
      '½ taza frijoles negros cocidos',
      '60 g arroz integral cocido',
      '½ cebolla picada, 2 dientes ajo, 1 tomate',
      'Sal, comino y chile en polvo al gusto',
    ],
    steps: [
      'Sofríe la cebolla y el ajo con una pizca de sal a fuego medio, 3 minutos.',
      'Agrega la carne molida y cocina rompiendo los grumos hasta dorar, 8 minutos.',
      'Añade el tomate y los frijoles, sazona con comino y chile. Cocina 4 minutos más.',
      'Sirve sobre el arroz integral.',
    ],
  },
  {
    id: 'cen-04',
    name: 'Pechuga de pollo en salsa de tomate con pasta integral',
    category: 'cena',
    prepMin: 5,
    cookMin: 15,
    kcal: 430,
    protein: 36,
    carbs: 48,
    fat: 8,
    ingredients: [
      '130 g pechuga de pollo en cubos',
      '80 g pasta integral cocida',
      '½ taza salsa de tomate natural (sin azúcar)',
      '1 diente de ajo, albahaca seca',
      'Sal y ½ cdita aceite de oliva',
    ],
    steps: [
      'Saltea el ajo en el aceite a fuego medio-bajo, 1 minuto.',
      'Agrega el pollo y dóralo 6 minutos, revolviendo ocasionalmente.',
      'Añade la salsa de tomate y cocina 5 minutos a fuego bajo. Sazona con sal y albahaca.',
      'Mezcla con la pasta cocida y sirve.',
    ],
  },
  {
    id: 'cen-05',
    name: 'Tacos de res magra con repollo y guacamole',
    category: 'cena',
    prepMin: 5,
    cookMin: 10,
    kcal: 400,
    protein: 32,
    carbs: 30,
    fat: 16,
    ingredients: [
      '2 tortillas de maíz (pequeñas)',
      '120 g carne de res magra molida',
      '1 taza repollo morado rallado fino',
      '2 cdas guacamole',
      'Jugo de 1 limón, sal y comino',
    ],
    steps: [
      'Sazona la carne con sal y comino. Cocína en sartén caliente 8 minutos, revolviendo.',
      'Calienta las tortillas directamente en la flama del quemador o en sartén seca, 20 segundos por lado.',
      'Arma los tacos: carne, repollo y guacamole. Exprime limón generosamente.',
    ],
  },
  {
    id: 'cen-06',
    name: 'Ensalada de camarones con pepino, aguacate y limón',
    category: 'cena',
    prepMin: 10,
    cookMin: 0,
    kcal: 290,
    protein: 28,
    carbs: 10,
    fat: 16,
    ingredients: [
      '150 g camarones cocidos y pelados',
      '1 pepino mediano en rodajas',
      '½ aguacate en cubos',
      '1 tomate en cubos',
      'Jugo de 1 limón, cilantro fresco, sal',
    ],
    steps: [
      'Mezcla en un bowl el pepino, el tomate y el aguacate.',
      'Agrega los camarones fríos.',
      'Aliña con el jugo de limón, sal y cilantro picado. Sirve frío.',
    ],
    tip: 'Opción de cena muy ligera y alta en proteína. Perfecta si cenaste abundante al almuerzo.',
  },
  {
    id: 'cen-07',
    name: 'Pechuga rellena de espinacas y queso ricotta',
    category: 'cena',
    prepMin: 8,
    cookMin: 25,
    kcal: 360,
    protein: 42,
    carbs: 6,
    fat: 18,
    ingredients: [
      '1 pechuga grande de pollo (160 g)',
      '2 cdas queso ricotta bajo en grasa',
      '1 taza espinacas baby',
      'Ajo en polvo, sal y pimienta',
      '½ cdita aceite de oliva',
    ],
    steps: [
      'Precalienta el horno a 190 °C.',
      'Abre la pechuga en forma de mariposa con un cuchillo afilado.',
      'Mezcla las espinacas con el ricotta, sal y ajo en polvo. Rellena la pechuga y cierra con palillos.',
      'Sella en sartén con el aceite 2 minutos por lado, luego hornea 20-22 minutos.',
    ],
  },

  // ─── SNACKS ─────────────────────────────────────────────────────────────────
  {
    id: 'snk-01',
    name: 'Huevos duros con sal y pimentón ahumado',
    category: 'snack',
    prepMin: 2,
    cookMin: 10,
    kcal: 160,
    protein: 12,
    carbs: 1,
    fat: 11,
    ingredients: [
      '2 huevos medianos',
      'Agua para hervir',
      'Sal y pimentón ahumado al gusto',
    ],
    steps: [
      'Hierve los huevos en agua por 9-10 minutos para yema firme.',
      'Enfría en agua helada por 2 minutos para facilitar el pelado.',
      'Pela y espolvorea sal y pimentón ahumado encima.',
    ],
    tip: 'Prepara 4-6 huevos el domingo y guárdalos en el refrigerador sin pelar. Duran hasta 5 días y tienes snack listo.',
  },
  {
    id: 'snk-02',
    name: 'Manzana con mantequilla de maní natural',
    category: 'snack',
    prepMin: 3,
    cookMin: 0,
    kcal: 190,
    protein: 5,
    carbs: 30,
    fat: 8,
    ingredients: [
      '1 manzana mediana',
      '1.5 cditas mantequilla de maní natural (sin azúcar añadida)',
    ],
    steps: [
      'Corta la manzana en gajos o bastones.',
      'Sirve la mantequilla de maní en un platito pequeño al lado.',
      'Usa los gajos de manzana para untar o dipear la mantequilla.',
    ],
    tip: 'Elige mantequilla de maní cuya lista de ingredientes diga solo "maní" y tal vez sal. Sin aceites hidrogenados ni azúcar.',
  },
  {
    id: 'snk-03',
    name: 'Cottage con fruta tropical',
    category: 'snack',
    prepMin: 3,
    cookMin: 0,
    kcal: 180,
    protein: 14,
    carbs: 22,
    fat: 3,
    ingredients: [
      '150 g queso cottage bajo en grasa',
      '½ taza mango o piña en cubos',
      '1 cdita miel (opcional)',
      'Canela en polvo al gusto',
    ],
    steps: [
      'Sirve el queso cottage en un bowl.',
      'Agrega la fruta tropical encima.',
      'Rocía con miel si deseas y espolvorea canela.',
    ],
    tip: 'El queso cottage es uno de los alimentos más proteicos por caloría que existen. Si no lo encuentras, sustitúyelo por ricotta baja en grasa.',
  },
  {
    id: 'snk-04',
    name: 'Zanahoria y apio con hummus casero',
    category: 'snack',
    prepMin: 5,
    cookMin: 0,
    kcal: 160,
    protein: 6,
    carbs: 20,
    fat: 7,
    ingredients: [
      '2 zanahorias medianas',
      '3 tallos de apio',
      '4 cdas hummus (de lata o casero)',
      'Paprika y jugo de limón para el hummus',
    ],
    steps: [
      'Corta las zanahorias y el apio en palitos del mismo largo.',
      'Sirve el hummus en un bowl pequeño, espolvorea paprika y unas gotas de limón.',
      'Usa los palitos de verdura como cucharas para el hummus.',
    ],
  },
  {
    id: 'snk-05',
    name: 'Mix de almendras, nueces y arándanos',
    category: 'snack',
    prepMin: 2,
    cookMin: 0,
    kcal: 200,
    protein: 6,
    carbs: 18,
    fat: 13,
    ingredients: [
      '15 g almendras sin sal (unas 12 unidades)',
      '10 g nueces (2-3 mitades)',
      '15 g arándanos secos (sin azúcar añadida)',
    ],
    steps: [
      'Mezcla los ingredientes en un recipiente pequeño.',
      'Consume como snack entre comidas.',
    ],
    tip: 'Prepara 5 porciones el lunes y guárdalas en bolsitas pequeñas para toda la semana. Llevar al trabajo o la bolsa es mucho más fácil así.',
  },
  {
    id: 'snk-06',
    name: 'Licuado de proteína con cacao y leche',
    category: 'snack',
    prepMin: 3,
    cookMin: 0,
    kcal: 240,
    protein: 28,
    carbs: 24,
    fat: 4,
    ingredients: [
      '1 scoop proteína de chocolate o vainilla (30 g)',
      '250 ml leche descremada',
      '1 cdita cacao en polvo sin azúcar',
      '3-4 cubos de hielo',
    ],
    steps: [
      'Agrega todos los ingredientes a la licuadora.',
      'Licúa 20-30 segundos hasta que el cacao quede bien integrado.',
      'Sirve frío e inmediatamente.',
    ],
    tip: 'El cacao sin azúcar agrega antioxidantes y profundiza el sabor sin agregar calorías significativas. No confundir con cocoa en polvo con azúcar.',
  },
  {
    id: 'snk-07',
    name: 'Jícama con chile, limón y sal',
    category: 'snack',
    prepMin: 5,
    cookMin: 0,
    kcal: 80,
    protein: 2,
    carbs: 18,
    fat: 0,
    ingredients: [
      '200 g jícama pelada',
      'Jugo de 1 limón',
      'Chile en polvo al gusto',
      'Sal al gusto',
    ],
    steps: [
      'Pela la jícama y córtala en bastones o en cubos.',
      'Mezcla con el jugo de limón.',
      'Espolvorea chile en polvo y sal al gusto.',
    ],
    tip: 'Si no encuentras jícama, sustitúyela por pepino o apio. El resultado es igual de refrescante. Excelente opción para los días de hambre extra sin romper el plan.',
  },
]

export const RECIPES_BY_CATEGORY = {
  desayuno: RECIPES.filter((r) => r.category === 'desayuno'),
  almuerzo: RECIPES.filter((r) => r.category === 'almuerzo'),
  cena: RECIPES.filter((r) => r.category === 'cena'),
  snack: RECIPES.filter((r) => r.category === 'snack'),
}

export const CATEGORY_LABEL: Record<Recipe['category'], string> = {
  desayuno: 'Desayuno',
  almuerzo: 'Almuerzo',
  cena: 'Cena',
  snack: 'Snack',
}
